// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260323092452_AddMissingOrganizationEventColumns")]
    partial class AddMissingOrganizationEventColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Attachment.Attachments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Models.Organization.Organizations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Models.OrganizationEvent.OrganizationEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ImageUrlId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserOrganizationBindingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageUrlId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationEvent");
                });

            modelBuilder.Entity("Models.OrganizationPost.OrganizationPosts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganizationsId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationsId");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("OrganizationPost");
                });

            modelBuilder.Entity("Models.Post.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrganizationEventId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId1")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationEventId");

                    b.HasIndex("UserId1");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Models.Role.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Models.User.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Models.UserEventBinding.UserEventBindings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationEventsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId1")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationEventsId")
                        .IsUnique();

                    b.HasIndex("UserId1");

                    b.ToTable("UserEventBinding");
                });

            modelBuilder.Entity("Models.UserOrganizationBinding.UserOrganizationBindings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId1")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserOrganizationBinding");
                });

            modelBuilder.Entity("Models.Attachment.Attachments", b =>
                {
                    b.HasOne("Models.Post.Posts", "Post")
                        .WithMany("Attachment")
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Models.OrganizationEvent.OrganizationEvents", b =>
                {
                    b.HasOne("Models.Attachment.Attachments", "ImageUrl")
                        .WithMany()
                        .HasForeignKey("ImageUrlId");

                    b.HasOne("Models.Organization.Organizations", "Organization")
                        .WithOne("OrganizationEvent")
                        .HasForeignKey("Models.OrganizationEvent.OrganizationEvents", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUrl");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Models.OrganizationPost.OrganizationPosts", b =>
                {
                    b.HasOne("Models.Organization.Organizations", null)
                        .WithMany("OrganizationPost")
                        .HasForeignKey("OrganizationsId");

                    b.HasOne("Models.Post.Posts", "Post")
                        .WithOne("PostId")
                        .HasForeignKey("Models.OrganizationPost.OrganizationPosts", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Models.Post.Posts", b =>
                {
                    b.HasOne("Models.OrganizationEvent.OrganizationEvents", "OrganizationEvent")
                        .WithMany()
                        .HasForeignKey("OrganizationEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("OrganizationEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserEventBinding.UserEventBindings", b =>
                {
                    b.HasOne("Models.OrganizationEvent.OrganizationEvents", "OrganizationEvent")
                        .WithOne("UserEventBinding")
                        .HasForeignKey("Models.UserEventBinding.UserEventBindings", "OrganizationEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User.Users", "User")
                        .WithMany("UserEventBindings")
                        .HasForeignKey("UserId1");

                    b.Navigation("OrganizationEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserOrganizationBinding.UserOrganizationBindings", b =>
                {
                    b.HasOne("Models.Organization.Organizations", "Organization")
                        .WithOne("UserOrganizationBindings")
                        .HasForeignKey("Models.UserOrganizationBinding.UserOrganizationBindings", "OrganizationId");

                    b.HasOne("Models.Role.Roles", "Role")
                        .WithMany("UserOrganizationBinding")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User.Users", "User")
                        .WithMany("UserOrganizationBindings")
                        .HasForeignKey("UserId1");

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Organization.Organizations", b =>
                {
                    b.Navigation("OrganizationEvent");

                    b.Navigation("OrganizationPost");

                    b.Navigation("UserOrganizationBindings");
                });

            modelBuilder.Entity("Models.OrganizationEvent.OrganizationEvents", b =>
                {
                    b.Navigation("UserEventBinding");
                });

            modelBuilder.Entity("Models.Post.Posts", b =>
                {
                    b.Navigation("Attachment");

                    b.Navigation("PostId")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Role.Roles", b =>
                {
                    b.Navigation("UserOrganizationBinding");
                });

            modelBuilder.Entity("Models.User.Users", b =>
                {
                    b.Navigation("UserEventBindings");

                    b.Navigation("UserOrganizationBindings");
                });
#pragma warning restore 612, 618
        }
    }
}
