on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to production
    runs-on: self-hosted
    steps:
    - run: |
        cd ~/backend
        git pull
        cd ~/backend/src
        dotnet run -e ASPNETCORE_ENVIRONMENT=development

