on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to production
    runs-on: self-hosted
    steps:
    - run: whoami
    # - run: cd ~/backend
    # - run: git pull
    - run: cd ~/backend && git pull
    - run: cd ~/backend/src
    - run: dotnet run -e ASPNETCORE_ENVIRONMENT=development

