on:
  push:
    branches:
    - dev

jobs:
  my_job:
    name: test dev
    runs-on: self-hosted
    steps:
    - run: |
        tmux send -t runnerBackendTesting:pane C-c
        tmux send -t runnerBackendTesting:pane "cd ~/backend_testing" ENTER
        tmux send -t runnerBackendTesting:pane "git pull" ENTER
        tmux send -t runnerBackendTesting:pane "export \$(cat .env)" ENTER
        tmux send -t runnerBackendTesting:pane "cd ~/backend_testing/src" ENTER
        tmux send -t runnerBackendTesting:pane "dotnet ef database update" ENTER
        tmux send -t runnerBackendTesting:pane "dotnet run -e ASPNETCORE_ENVIRONMENT=development" ENTER
        tmux send -t runnerBackendTesting:runTests C-c
        tmux send -t runnerBackendTesting:runTests "cd ~/backend_testing" ENTER
        tmux send -t runnerBackendTesting:runTests "export \$(cat .env)" ENTER
        tmux send -t runnerBackendTesting:runTests "sleep 120 && dotnet test" ENTER
        tmux send -t runnerBackend:pane C-c
        tmux send -t runnerBackend:pane "cd ~/backend" ENTER
        tmux send -t runnerBackend:pane "git pull" ENTER
        tmux send -t runnerBackend:pane "export \$(cat .env)" ENTER
        tmux send -t runnerBackend:pane "cd ~/backend/src" ENTER
        tmux send -t runnerBackend:pane "dotnet ef database update" ENTER
        tmux send -t runnerBackend:pane "dotnet run" ENTER
